# Generated by Django 4.0.4 on 2022-06-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media/default.jpeg', upload_to='media/avatars/'),
        ),
    ]
