# Generated by Django 4.0.4 on 2022-05-10 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Group',
        ),
    ]
